#!/usr/bin/env python3
"""Generate Modules/FlightTimer/Data.lua from the client's taxi tables.

The flown length of a route is the Catmull-Rom spline through its TaxiPathNode points, which is the
curve a flight follows. Transports (paths that change continent) and paths without both end nodes
are left out. Input: TaxiPath, TaxiPathNode and TaxiNodes as wago.tools CSV exports of the build,
downloaded unless --source-dir holds them already.
"""
import argparse
import csv
import io
import math
from pathlib import Path
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / 'Modules' / 'FlightTimer' / 'Data.lua'
TABLES = ('TaxiPath', 'TaxiPathNode', 'TaxiNodes')
STEPS = 20  # samples per spline segment; more changes no length by a yard


def read(table, build, source_dir):
    if source_dir:
        text = (Path(source_dir) / f'{table}.csv').read_text(encoding='utf-8')
    else:
        url = f'https://wago.tools/db2/{table}/csv?build={build}'
        with urllib.request.urlopen(url, timeout=60) as response:
            text = response.read().decode('utf-8')
    return list(csv.DictReader(io.StringIO(text)))


def catmull_rom(p0, p1, p2, p3, t):
    return tuple(0.5 * (2 * b + (c - a) * t + (2 * a - 5 * b + 4 * c - d) * t * t + (3 * b - a - 3 * c + d) * t ** 3)
                 for a, b, c, d in zip(p0, p1, p2, p3))


def spline_length(points):
    """Length of the spline through points, the end points doubled as their own neighbours."""
    length = 0
    for i in range(len(points) - 1):
        p0, p1, p2, p3 = points[max(i - 1, 0)], points[i], points[i + 1], points[min(i + 2, len(points) - 1)]
        previous = p1
        for step in range(1, STEPS + 1):
            point = catmull_rom(p0, p1, p2, p3, step / STEPS)
            length += math.dist(previous, point)
            previous = point
    return length


def routes(paths, path_nodes, nodes):
    known = {int(row['ID']) for row in nodes}
    assert max(known) < 10000, 'node ids no longer fit the fromNodeID * 10000 + toNodeID key'
    by_path = {}
    for row in path_nodes:
        by_path.setdefault(int(row['PathID']), []).append(
            (int(row['NodeIndex']), int(row['ContinentID']), (float(row['Loc_0']), float(row['Loc_1']), float(row['Loc_2']))))
    result = {}
    for row in paths:
        source, target = int(row['FromTaxiNode']), int(row['ToTaxiNode'])
        points = sorted(by_path.get(int(row['ID']), []))
        if source not in known or target not in known or len(points) < 2 or len({p[1] for p in points}) > 1:
            continue
        length = round(spline_length([p[2] for p in points]))
        if length > 0:
            result[source * 10000 + target] = length
    return result


def check():
    # Points on a line: the spline is the line.
    assert round(spline_length([(0, 0, 0), (3, 0, 0), (10, 0, 0)]), 6) == 10
    # A corner bows out a little: the curve passes every point, so it is a bit longer than the polyline.
    assert 200 < spline_length([(0, 0, 0), (100, 0, 0), (100, 100, 0)]) < 210
    paths = [{'ID': '1', 'FromTaxiNode': '2', 'ToTaxiNode': '3'}, {'ID': '2', 'FromTaxiNode': '2', 'ToTaxiNode': '9'},
             {'ID': '3', 'FromTaxiNode': '3', 'ToTaxiNode': '2'}]
    path_nodes = [{'PathID': pid, 'NodeIndex': index, 'ContinentID': continent, 'Loc_0': x, 'Loc_1': '0', 'Loc_2': '0'}
                  for pid, index, continent, x in (('1', '1', '0', '50'), ('1', '0', '0', '0'), ('2', '0', '0', '0'),
                                                   ('2', '1', '0', '10'), ('3', '0', '0', '0'), ('3', '1', '1', '10'))]
    nodes = [{'ID': '2'}, {'ID': '3'}]
    # Unknown end node (9) and a continent change (path 3) drop out; node order follows NodeIndex.
    assert routes(paths, path_nodes, nodes) == {20003: 50}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--build', default='1.60.1.69913')
    parser.add_argument('--source-dir', help='folder with TaxiPath.csv, TaxiPathNode.csv and TaxiNodes.csv')
    parser.add_argument('--check', action='store_true', help='run the self-check only')
    args = parser.parse_args()
    check()
    if args.check:
        return
    lengths = routes(*(read(table, args.build, args.source_dir) for table in TABLES))
    lines = ['local _, ns = ...',
             f'-- Generated by tools/build-flight-routes.py from the TaxiPath tables of WoW Forever build {args.build}.',
             '-- Flown length of each flight route in yards, keyed fromNodeID * 10000 + toNodeID.',
             'ns.flightTimerRoutes = {']
    lines += [f'    [{key}] = {lengths[key]},' for key in sorted(lengths)]
    lines.append('}')
    DEST.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'{DEST.relative_to(ROOT)}: {len(lengths)} routes')


if __name__ == '__main__':
    main()
